// Lista de imágenes para la sección Carrusel 2
// Agrega aquí las rutas de las imágenes de productos para carrusel2

const imagenesCarrusel2 = [
  'assets/img/carrusel2/2.jpeg',
  'assets/img/carrusel2/3.jpeg',
  'assets/img/carrusel2/4.jpeg',
  'assets/img/carrusel2/5.jpeg',
  'assets/img/carrusel2/6.jpeg',
  'assets/img/carrusel2/7.jpeg',
  'assets/img/carrusel2/8.jpeg',
  'assets/img/carrusel2/9.jpeg',
  'assets/img/carrusel2/10.jpeg',
  'assets/img/carrusel2/11.jpeg',
  'assets/img/carrusel2/12.jpeg',
  'assets/img/carrusel2/13.jpeg',
  'assets/img/carrusel2/14.jpeg',
  'assets/img/carrusel2/15.jpeg',
  'assets/img/carrusel2/16.jpeg',
  'assets/img/carrusel2/17.jpeg',
  'assets/img/carrusel2/18.jpeg',
  'assets/img/carrusel2/19.jpeg',
  'assets/img/carrusel2/20.jpeg',
  'assets/img/carrusel2/21.jpeg',
  'assets/img/carrusel2/22.jpeg',
  'assets/img/carrusel2/23.jpeg',
  'assets/img/carrusel2/24.jpeg',
  'assets/img/carrusel2/25.jpeg',
  'assets/img/carrusel2/26.jpeg',
  'assets/img/carrusel2/27.jpeg',
  'assets/img/carrusel2/28.jpeg',
  'assets/img/carrusel2/29.jpeg',
  'assets/img/carrusel2/30.jpeg',
  'assets/img/carrusel2/31.jpeg',
  'assets/img/carrusel2/32.jpeg',
  'assets/img/carrusel2/33.jpeg',
  'assets/img/carrusel2/34.jpeg',
  'assets/img/carrusel2/zapato1.jpeg',
];
