// Lista de imágenes para la sección Hombres
// Agrega aquí las rutas de las imágenes de productos para hombres

const imagenesHombres = [
  'assets/img/calzhombres/2.jpeg',
  'assets/img/calzhombres/3.jpeg',
  'assets/img/calzhombres/4.jpeg',
  'assets/img/calzhombres/5.jpeg',
  'assets/img/calzhombres/6.jpeg',
  'assets/img/calzhombres/7.jpeg',
  'assets/img/calzhombres/8.jpeg',
  'assets/img/calzhombres/9.jpeg',
  'assets/img/calzhombres/10.jpeg',
  'assets/img/calzhombres/11.jpeg',
  'assets/img/calzhombres/12.jpeg',
  'assets/img/calzhombres/13.jpeg',
  'assets/img/calzhombres/14.jpeg',
  'assets/img/calzhombres/15.jpeg',
  'assets/img/calzhombres/16.jpeg',
  'assets/img/calzhombres/17.jpeg',
  'assets/img/calzhombres/18.jpeg',
  'assets/img/calzhombres/19.jpeg',
  'assets/img/calzhombres/20.jpeg',
  'assets/img/calzhombres/21.jpeg',
  'assets/img/calzhombres/22.jpeg',
  'assets/img/calzhombres/23.jpeg',
  'assets/img/calzhombres/24.jpeg',
  'assets/img/calzhombres/25.jpeg',
  'assets/img/calzhombres/26.jpeg',
  'assets/img/calzhombres/27.jpeg',
  'assets/img/calzhombres/28.jpeg',
  'assets/img/calzhombres/29.jpeg',
  'assets/img/calzhombres/30.jpeg',
  'assets/img/calzhombres/31.jpeg',
  'assets/img/calzhombres/32.jpeg',
  'assets/img/calzhombres/33.jpeg',
  'assets/img/calzhombres/34.jpeg',
  'assets/img/calzhombres/zapato1.jpeg',
];
